### ISSUE TITLE
Not able to use in Maven Java Project

### ISSUE THREAD

**Issue by harmandeeps** [ishugaliy/allgood-consistent-hash#4]
Hi,

I have been trying to use it in maven project by following the instructions (https://github.com/ishugaliy/allgood-consistent-hash#maven), but it is not working also, I saw [https://maven.pkg.github.com/ishugaliy/allgood-consistent-hash] throws 404 error. Can you please help me with this?

**Comment by ishugaliy** [comment]
Hi! 

In order to get it as Maven dependencies, GitHub required for all consumers to be authenticated with GitHub via access token.
This is the full guide from Github how to use package:
https://docs.github.com/en/packages/using-github-packages-with-your-projects-ecosystem/configuring-apache-maven-for-use-with-github-packages

In your case, I assume that issue may be caused by the next:
1. Make sure you place `settings.xml` file under maven root folder `~/.m2/settings.xml` and not inside your project.
2. Once profile and repository were defined inside `settings.xml` file, you also need to add GitHub credentials to it:
```
<servers>
    <server>
        <id>github</id>
        <username>{your_github_username}</username>
        <password>{your_github_access_token}</password>
    </server>
</servers>
```
Where:

> **username** - is you GitHub account username

> **password** - generate access token in your account settings with `read:packages` access scope, in this way you are not exposing your password and use the token instead. If you have trouble with that, please follow[ this guide](https://docs.github.com/en/github/authenticating-to-github/creating-a-personal-access-token) to generate an access token.

**Comment by harmandeeps** [comment]
Hi Ishugaliy

Thank you for the prompt response. I followed all the steps as mentioned, but forgot to add `<activeProfile>github</activeProfile>` in settings.xml. With this, it is working fine. I can push the changes in README with this step if you think this is needed.

**Comment by ishugaliy** [comment]
@harmandeeps yes, that would be great. Thanks
